[TSK2-33] モックを追加
azurata09/funverse_server pull request #2
Opened 2024-12-12 04:48 UTC by azurata09

2024-12-13 05:16 UTC, asann3 requested changes
見ました

2024-12-13 05:16 UTC, asann3 commented on mock/openapi.yml
> +openapi: 3.0.0
```suggestion
openapi: 3.1.0
```

2024-12-13 05:16 UTC, asann3 commented on mock/compose.yml
> +version: '3.9'
```suggestion
```
Docker Compose V2 ではバージョンを書かないことが推奨されているようなので削除して良さそう

2024-12-13 08:20 UTC, azurata09 commented on mock/compose.yml
> +version: '3.9'
これ、Warningとして出てたけど「まあいっか」と放置してた案件だった

2024-12-13 11:22 UTC, asann3 commented on mock/openapi.yml
> +    description: ローカルサーバー
```suggestion
```
これも使っていないから要らないかも
残すなら`mock/compose.yml`とアドレス統一した方が親切

2024-12-13 14:06 UTC, azurata09 commented on mock/openapi.yml
> +    description: ローカルサーバー
開発用に残しているつもりだった

結局起動したら`ポート3000番で起動`みたいなことが出てくるっちゃ出てくる

2024-12-16 01:37 UTC, asann3 commented on mock/openapi.yml
> +    description: ローカルサーバー
なるほど、じゃあ残しておいてもいいか

2024-12-16 01:38 UTC, asann3 approved these changes
LGTM

2024-12-16 07:52 UTC, merged